{-# LANGUAGE OverloadedStrings #-}

{- | A small chat page for local use, served at @\/@.

It is one self-contained HTML document: no build step, no assets, no
libraries. It talks to the same JSON API as any other client, so it is also
a worked example of that API — starting a session, following its event
stream, and completing deferred tool calls.

It is meant for a person at the machine running the server. 'uiEnabled'
keeps it to loopback binds unless the server also authenticates its callers.
-}
module AgentsServer.UI (
    uiPage,
    uiEnabled,
) where

import Data.Text (Text)
import qualified Data.Text as Text

{- | Whether to serve the page: on a loopback bind, or when callers are
authenticated. On a public bind without tokens the API refuses browser
requests anyway (the Origin check), so the page could only mislead.
-}
uiEnabled :: Text -> Bool -> Bool
uiEnabled bind authenticated =
    authenticated || bind `elem` ["127.0.0.1", "localhost", "::1", "[::1]"]

-- | The page. Attributes are single-quoted so the markup needs no escaping.
uiPage :: Text
uiPage =
    Text.unlines
        [ "<!DOCTYPE html>"
        , "<html lang='en'><head><meta charset='utf-8'>"
        , "<meta name='viewport' content='width=device-width, initial-scale=1'>"
        , "<title>agents</title>"
        , "<style>"
        , ":root{--bg:#1b1c1d;--panel:#232425;--edge:#34363a;--fg:#ececec;--dim:#9aa0a6;--accent:#7aa2f7;--warn:#e0af68}"
        , "*{box-sizing:border-box}"
        , "body{margin:0;height:100vh;display:flex;background:var(--bg);color:var(--fg);"
        , "font:15px/1.6 ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,sans-serif}"
        , "aside{width:270px;flex:none;background:var(--panel);border-right:1px solid var(--edge);"
        , "display:flex;flex-direction:column;padding:14px;gap:12px;overflow:hidden}"
        , "aside h1{font-size:15px;margin:0;letter-spacing:.3px}"
        , "select,input,textarea,button{font:inherit;color:inherit;background:#2b2d2f;"
        , "border:1px solid var(--edge);border-radius:8px;padding:8px 10px;width:100%}"
        , "button{cursor:pointer;background:#303235}button:hover{background:#3a3d40}"
        , "button.primary{background:var(--accent);color:#11151f;border-color:transparent;font-weight:600}"
        , "#sessions{flex:1;overflow-y:auto;display:flex;flex-direction:column;gap:4px;margin:0;padding:0;list-style:none}"
        , "#sessions li{padding:8px 10px;border-radius:8px;cursor:pointer;font-size:13px;color:var(--dim);"
        , "white-space:nowrap;overflow:hidden;text-overflow:ellipsis}"
        , "#sessions li:hover{background:#2b2d2f}#sessions li.on{background:#2b2d2f;color:var(--fg)}"
        , "main{flex:1;display:flex;flex-direction:column;min-width:0}"
        , "header{padding:12px 20px;border-bottom:1px solid var(--edge);display:flex;align-items:center;gap:10px}"
        , "#status{font-size:12px;color:var(--dim);border:1px solid var(--edge);border-radius:999px;padding:2px 10px}"
        , "#log{flex:1;overflow-y:auto;padding:24px;display:flex;flex-direction:column;gap:18px}"
        , ".msg{max-width:min(760px,90%);white-space:pre-wrap;word-wrap:break-word}"
        , ".msg.user{align-self:flex-end;background:#2f3336;padding:10px 14px;border-radius:14px}"
        , ".msg .who{font-size:11px;text-transform:uppercase;letter-spacing:.7px;color:var(--dim);margin-bottom:4px}"
        , ".tools{font-size:12px;color:var(--dim);font-family:ui-monospace,SFMono-Regular,Menlo,monospace}"
        , ".card{border:1px solid var(--warn);border-radius:10px;padding:12px;background:#26231c}"
        , ".card h3{margin:0 0 6px;font-size:13px;color:var(--warn)}"
        , ".card pre{margin:0 0 8px;font-size:12px;white-space:pre-wrap;color:var(--dim)}"
        , "footer{padding:14px 20px;border-top:1px solid var(--edge);display:flex;gap:10px;align-items:flex-end}"
        , "#prompt{resize:none;max-height:180px}"
        , "footer button{width:auto;flex:none}"
        , ".hint{font-size:12px;color:var(--dim)}"
        , "a{color:var(--accent)}"
        , "</style></head><body>"
        , "<aside>"
        , "  <h1>agents</h1>"
        , "  <select id='agent'></select>"
        , "  <button id='new'>New chat</button>"
        , "  <ul id='sessions'></ul>"
        , "  <input id='token' type='password' placeholder='Bearer token, if required'>"
        , "  <div class='hint'><a href='/openapi.json'>openapi.json</a></div>"
        , "</aside>"
        , "<main>"
        , "  <header><strong id='title'>New chat</strong><span id='status'>&mdash;</span></header>"
        , "  <div id='log'></div>"
        , "  <footer>"
        , "    <textarea id='prompt' rows='1' placeholder='Ask something. Enter sends, Shift+Enter adds a line.'></textarea>"
        , "    <button class='primary' id='send'>Send</button>"
        , "  </footer>"
        , "</main>"
        , "<script>"
        , jsSource
        , "</script></body></html>"
        ]

-- | The page's behaviour. Kept apart so the markup above stays readable.
jsSource :: Text
jsSource =
    Text.unlines
        [ "const $ = s => document.querySelector(s);"
        , "let sid = null, es = null, streaming = null;"
        , "const token = () => sessionStorage.getItem('token') || '';"
        , "$('#token').value = token();"
        , "$('#token').oninput = e => sessionStorage.setItem('token', e.target.value);"
        , ""
        , "async function api(path, opts = {}) {"
        , "  const h = Object.assign({'Content-Type': 'application/json'}, opts.headers || {});"
        , "  if (token()) h['Authorization'] = 'Bearer ' + token();"
        , "  const r = await fetch(path, Object.assign({}, opts, {headers: h}));"
        , "  const body = r.status === 204 ? null : await r.json().catch(() => null);"
        , "  if (!r.ok) throw new Error(body && body.message ? body.message : r.status + ' ' + r.statusText);"
        , "  return body;"
        , "}"
        , ""
        , "function note(text, cls) {"
        , "  const d = document.createElement('div');"
        , "  d.className = 'msg ' + (cls || '');"
        , "  d.textContent = text;"
        , "  $('#log').appendChild(d);"
        , "  $('#log').scrollTop = $('#log').scrollHeight;"
        , "  return d;"
        , "}"
        , ""
        , "// The text a user turn carries; queryText is a bare string unless it has media."
        , "function userText(c) {"
        , "  const q = c && c.userQuery;"
        , "  if (!q) return null;"
        , "  return typeof q === 'string' ? q : q.queryText;"
        , "}"
        , ""
        , "function render(session, pending) {"
        , "  const log = $('#log');"
        , "  log.innerHTML = '';"
        , "  streaming = null;"
        , "  const turns = (session && session.turns ? session.turns : []).slice().reverse();"
        , "  for (const turn of turns) {"
        , "    const c = turn.contents || {};"
        , "    if (turn.tag === 'UserTurn' || turn.tag === 'PartialUserTurn') {"
        , "      const t = userText(c);"
        , "      if (t) note(t, 'user');"
        , "    } else if (turn.tag === 'LlmTurn') {"
        , "      const r = c.llmResponse || {};"
        , "      const d = document.createElement('div');"
        , "      d.className = 'msg';"
        , "      d.innerHTML = '<div class=\\'who\\'>agent</div>';"
        , "      d.appendChild(document.createTextNode(r.responseText || ''));"
        , "      const calls = c.llmToolCalls || [];"
        , "      if (calls.length) {"
        , "        const s = document.createElement('div');"
        , "        s.className = 'tools';"
        , "        s.textContent = 'called ' + calls.map(x => (x.function || {}).name).join(', ');"
        , "        d.appendChild(s);"
        , "      }"
        , "      log.appendChild(d);"
        , "    }"
        , "  }"
        , "  for (const call of pending || []) deferredCard(call);"
        , "  log.scrollTop = log.scrollHeight;"
        , "}"
        , ""
        , "// A deferred call is one this server will not run: a worker answers it."
        , "function deferredCard(call) {"
        , "  const box = document.createElement('div');"
        , "  box.className = 'card';"
        , "  const h = document.createElement('h3');"
        , "  h.textContent = 'waiting on ' + call.tool;"
        , "  const args = document.createElement('pre');"
        , "  args.textContent = ((call.call || {}).function || {}).arguments || '';"
        , "  const input = document.createElement('textarea');"
        , "  input.rows = 2;"
        , "  input.placeholder = 'The result of this call';"
        , "  const go = document.createElement('button');"
        , "  go.textContent = 'Send result';"
        , "  go.onclick = async () => {"
        , "    go.disabled = true;"
        , "    try {"
        , "      await api('/v1/continuations/' + call.continuation_token, {"
        , "        method: 'POST', body: JSON.stringify({result: input.value})"
        , "      });"
        , "      box.remove();"
        , "    } catch (e) { go.disabled = false; note('could not send: ' + e.message); }"
        , "  };"
        , "  box.append(h, args, input, go);"
        , "  $('#log').appendChild(box);"
        , "}"
        , ""
        , "async function refresh() {"
        , "  if (!sid) return;"
        , "  const s = await api('/v1/sessions/' + sid);"
        , "  $('#status').textContent = s.status;"
        , "  render(s.session, s.pending);"
        , "}"
        , ""
        , "function follow(id) {"
        , "  if (es) es.close();"
        , "  // EventSource cannot set headers, so a token travels as a query parameter,"
        , "  // which this server accepts on this endpoint only."
        , "  const q = token() ? '?access_token=' + encodeURIComponent(token()) : '';"
        , "  es = new EventSource('/v1/sessions/' + id + '/events' + q);"
        , "  es.addEventListener('text.delta', e => {"
        , "    const d = JSON.parse(e.data);"
        , "    if (!streaming) { streaming = note('', ''); }"
        , "    streaming.textContent += d.text;"
        , "    $('#log').scrollTop = $('#log').scrollHeight;"
        , "  });"
        , "  for (const kind of ['session.updated', 'run.stopped', 'calls.deferred', 'session.failed']) {"
        , "    es.addEventListener(kind, () => refresh().catch(() => {}));"
        , "  }"
        , "  es.addEventListener('snapshot', e => { $('#status').textContent = JSON.parse(e.data).status; });"
        , "}"
        , ""
        , "async function openSession(id, title) {"
        , "  sid = id;"
        , "  $('#title').textContent = title || id.slice(0, 8);"
        , "  for (const li of document.querySelectorAll('#sessions li')) li.classList.toggle('on', li.dataset.id === id);"
        , "  await refresh();"
        , "  follow(id);"
        , "}"
        , ""
        , "async function listSessions() {"
        , "  const r = await api('/v1/sessions?limit=50');"
        , "  const ul = $('#sessions');"
        , "  ul.innerHTML = '';"
        , "  for (const s of r.sessions) {"
        , "    const li = document.createElement('li');"
        , "    li.dataset.id = s.session_id;"
        , "    li.textContent = (s.agent || 'session') + ' · ' + s.status;"
        , "    li.classList.toggle('on', s.session_id === sid);"
        , "    li.onclick = () => openSession(s.session_id, s.agent);"
        , "    ul.appendChild(li);"
        , "  }"
        , "}"
        , ""
        , "async function send() {"
        , "  const text = $('#prompt').value.trim();"
        , "  if (!text) return;"
        , "  $('#prompt').value = '';"
        , "  note(text, 'user');"
        , "  try {"
        , "    if (sid) {"
        , "      await api('/v1/sessions/' + sid + '/messages', {method: 'POST', body: JSON.stringify({prompt: text})});"
        , "    } else {"
        , "      const s = await api('/v1/sessions', {"
        , "        method: 'POST',"
        , "        body: JSON.stringify({agent: $('#agent').value, prompt: text})"
        , "      });"
        , "      await openSession(s.session_id, s.agent);"
        , "      await listSessions();"
        , "    }"
        , "  } catch (e) { note('could not send: ' + e.message); }"
        , "}"
        , ""
        , "$('#send').onclick = send;"
        , "$('#prompt').onkeydown = e => {"
        , "  if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send(); }"
        , "};"
        , "$('#prompt').oninput = e => {"
        , "  e.target.style.height = 'auto';"
        , "  e.target.style.height = e.target.scrollHeight + 'px';"
        , "};"
        , "$('#new').onclick = () => {"
        , "  if (es) es.close();"
        , "  sid = null;"
        , "  $('#title').textContent = 'New chat';"
        , "  $('#status').textContent = '\\u2014';"
        , "  $('#log').innerHTML = '';"
        , "  listSessions().catch(() => {});"
        , "};"
        , ""
        , "(async function start() {"
        , "  try {"
        , "    const agents = await api('/v1/agents');"
        , "    for (const a of agents) {"
        , "      const o = document.createElement('option');"
        , "      o.value = a.slug;"
        , "      o.textContent = a.slug + (a.description ? ' - ' + a.description : '');"
        , "      $('#agent').appendChild(o);"
        , "    }"
        , "    if (!agents.length) note('This server has no agents.');"
        , "    await listSessions();"
        , "  } catch (e) {"
        , "    note('Could not reach the API: ' + e.message + (token() ? '' : ' — a bearer token may be required.'));"
        , "  }"
        , "})();"
        ]
